name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: tp_devops
          POSTGRES_USER: tp_devops
          POSTGRES_DB: tp_devops
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew check

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: paomcber/tp-devops
          tag_with_ref: true

      # - name: Build image
      #   run: docker build ./docker --tag paomcber/tp-devops










        # if [ -f docker-compose.test.yml ]; then
        #     docker-compose --file docker-compose.test.yml build
        #     docker-compose --file docker-compose.test.yml run sut
        #   else
        #     docker build ./docker
        #   fi